version: "2"  

services:  
  postgres:
    image: postgres:11
    container_name: postgres-11
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=gobarber
    - POSTGRES_PASSWORD=docker
  mongo:
    image: mongo
    container_name: mongobarber
    ports:
    - 27017:27017
  redis:
    image: redis:alpine
    container_name: redis
    ports:
    - 6379:6379
    restart: always
